services:
  app:
    environment:
      APPLICATION_ENV: development
      docker: 1
    ports:
      - 8080:80
    expose:
      - 8080

  db:
    environment:
      MYSQL_DATABASE: slim-nextras-orm-dev
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_MAX_ALLOWED_PACKET: 1024M
      MYSQL_INNODB_BUFFER_POOL_SIZE: 2G
      MYSQL_INNODB_LOG_FILE_SIZE: 500M
      MYSQL_INNODB_LOG_BUFFER_SIZE: 256M

  adminer:
    ports:
      - 8081:8080
    environment:
      ADMINER_DB: slim-nextras-orm-dev
      ADMINER_DRIVER: server
      ADMINER_SERVER: db
      ADMINER_USERNAME: root
      ADMINER_PASSWORD: root
      ADMINER_AUTOLOGIN: 1

